In [47]:
import pandas as pd
import numpy as np

# Standardization

In [48]:
df = pd.read_csv(r'C:/Users/Kismet/Documents/我的坚果云/data_mining20170318/第八节课-特征工程/forestfires.csv',engine='python')
df.head()

   X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

In [49]:
df1= df.loc[:,'FFMC':'rain']
df1.head()

   FFMC   DMC     DC  ISI  temp  RH  wind  rain
0  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0
1  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0
2  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0
3  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2
4  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0

In [50]:
from sklearn.cross_validation import train_test_split

In [51]:
trainX,testX,trainY,testY = train_test_split(df1,df['area'],train_size=0.7)

In [52]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(trainX)
trainX_std = ss.transform(trainX)
testX_std = ss.transform(testX)

In [53]:
testX_std.shape

(156, 8)

In [54]:
testX.shape

(156, 8)

In [55]:
testX_std.mean(axis=0)   #平均值无限接近0

array([-0.00827671, -0.04413132, -0.02489652,  0.1383149 , -0.05954916,
        0.09580779,  0.02935358, -0.06744744])

In [56]:
testX_std.std(axis=0)    #标准差无限接近1

array([ 1.26814504,  0.93325596,  0.97876621,  1.30553756,  0.96505919,
        0.99848753,  0.98172555,  0.18184566])

In [57]:
from sklearn.preprocessing import MinMaxScaler

In [58]:
mms = MinMaxScaler((0,2))   #在（0，2）范围内
mms.fit(trainX)
mms.transform(trainX)

array([[ 1.59388646,  0.02920723,  0.02548973, ...,  0.47619048,
         0.6       ,  0.        ],
       [ 1.6069869 ,  0.14951321,  0.13405712, ...,  0.57142857,
         0.6       ,  0.        ],
       [ 1.77292576,  1.14394993,  1.75761152, ...,  1.11904762,
         1.11111111,  0.        ],
       ...,
       [ 1.8209607 ,  0.67176634,  1.74038235, ...,  0.47619048,
         1.        ,  0.        ],
       [ 1.8558952 ,  0.93602225,  1.6485721 , ...,  0.45238095,
         0.4       ,  0.        ],
       [ 1.80349345,  0.21488178,  0.16426717, ...,  0.26190476,
         0.91111111,  0.        ]])

# Normalization标准化

In [59]:
#假设样本和样本之间是独立的，不能说feature之间是独立的

In [60]:
from sklearn.preprocessing import Normalizer
norm = Normalizer()
norm.fit(trainX)
norm.transform(trainX)      #对每一个样本做normalization

array([[ 0.90270673,  0.06856   ,  0.19425335, ...,  0.36357578,
         0.03220243,  0.        ],
       [ 0.73423776,  0.20124177,  0.54478421, ...,  0.32838615,
         0.02610249,  0.        ],
       [ 0.11682055,  0.2142566 ,  0.96614449, ...,  0.07959203,
         0.00693221,  0.        ],
       ...,
       [ 0.12140202,  0.13049728,  0.98242046, ...,  0.0461354 ,
         0.00645896,  0.        ],
       [ 0.12783155,  0.1885137 ,  0.97201514, ...,  0.04678442,
         0.00302723,  0.        ],
       [ 0.71179178,  0.25848055,  0.60156884, ...,  0.20181664,
         0.0349298 ,  0.        ]])

# Binarization二分类

In [61]:
#将连续型的变量离散化

In [62]:
df['DC'].mean()

547.9400386847191

In [63]:
from sklearn.preprocessing import Binarizer
bi = Binarizer()
DC_bi = bi.fit_transform(df['DC'])
DC_bi.shape

C:\Users\Kismet\Anaconda3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\Kismet\Anaconda3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)

(1, 517)

In [64]:
df['DC_bi'] = DC_bi[0,:]

In [65]:
df.head()

   X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area  DC_bi
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0    1.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0    1.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0    1.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0    1.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0    1.0

In [66]:
help(pd.cut)

Help on function cut in module pandas.core.reshape.tile:

cut(x, bins, right=True, labels=None, retbins=False, precision=3, include_lowest=False)
    Return indices of half-open bins to which each value of `x` belongs.

    Parameters
    ----------
    x : array-like
        Input array to be binned. It has to be 1-dimensional.
    bins : int, sequence of scalars, or IntervalIndex
        If `bins` is an int, it defines the number of equal-width bins in the
        range of `x`. However, in this case, the range of `x` is extended
        by .1% on each side to include the min or max values of `x`. If
        `bins` is a sequence it defines the bin edges allowing for
        non-uniform bin width. No extension of the range of `x` is done in
        this case.
    right : bool, optional
        Indicates whether the bins include the rightmost edge or not. If
        right == True (the default), then the bins [1,2,3,4] indicate
        (1,2], (2,3], (3,4].
    labels : array or boolean, default None
        Used as labels for the resulting bins. Must be of the same length as
        the resulting bins. If False, return only integer indicators of the
        bins.
    retbins : bool, optional
        Whether to return the bins or not. Can be useful if bins is given
        as a scalar.
    precision : int, optional
        The precision at which to store and display the bins labels
    include_lowest : bool, optional
        Whether the first interval should be left-inclusive or not.

    Returns
    -------
    out : Categorical or Series or array of integers if labels is False
        The return type (Categorical or Series) depends on the input: a Series
        of type category if input is a Series else Categorical. Bins are
        represented as categories when categorical data is returned.
    bins : ndarray of floats
        Returned only if `retbins` is True.

    Notes
    -----
    The `cut` function can be useful for going from a continuous variable to
    a categorical variable. For example, `cut` could convert ages to groups
    of age ranges.

    Any NA values will be NA in the result.  Out of bounds values will be NA in
    the resulting Categorical object


    Examples
    --------
    >>> pd.cut(np.array([.2, 1.4, 2.5, 6.2, 9.7, 2.1]), 3, retbins=True)
    ([(0.191, 3.367], (0.191, 3.367], (0.191, 3.367], (3.367, 6.533],
      (6.533, 9.7], (0.191, 3.367]]
    Categories (3, object): [(0.191, 3.367] < (3.367, 6.533] < (6.533, 9.7]],
    array([ 0.1905    ,  3.36666667,  6.53333333,  9.7       ]))

    >>> pd.cut(np.array([.2, 1.4, 2.5, 6.2, 9.7, 2.1]), 3,
               labels=["good","medium","bad"])
    [good, good, good, medium, bad, good]
    Categories (3, object): [good < medium < bad]

    >>> pd.cut(np.ones(5), 4, labels=False)
    array([1, 1, 1, 1, 1], dtype=int64)

In [67]:
pd.cut(df['DC'],5)

0       (7.047, 178.44]
1      (519.52, 690.06]
2      (519.52, 690.06]
3       (7.047, 178.44]
4       (7.047, 178.44]
5      (348.98, 519.52]
6      (348.98, 519.52]
7      (519.52, 690.06]
8       (690.06, 860.6]
9       (690.06, 860.6]
10      (690.06, 860.6]
11      (690.06, 860.6]
12     (519.52, 690.06]
13     (519.52, 690.06]
14      (690.06, 860.6]
15      (690.06, 860.6]
16      (7.047, 178.44]
17     (519.52, 690.06]
18      (7.047, 178.44]
19      (7.047, 178.44]
20      (690.06, 860.6]
21      (690.06, 860.6]
22     (178.44, 348.98]
23     (519.52, 690.06]
24     (519.52, 690.06]
25     (519.52, 690.06]
26     (519.52, 690.06]
27     (519.52, 690.06]
28      (690.06, 860.6]
29      (690.06, 860.6]
             ...
487    (519.52, 690.06]
488    (519.52, 690.06]
489    (519.52, 690.06]
490    (519.52, 690.06]
491    (519.52, 690.06]
492    (519.52, 690.06]
493    (519.52, 690.06]
494    (519.52, 690.06]
495    (519.52, 690.06]
496    (519.52, 690.06]
497    (519.52, 690.06]
498    (519.52, 690.06]
499    (519.52, 690.06]
500    (519.52, 690.06]
501    (519.52, 690.06]
502    (519.52, 690.06]
503    (519.52, 690.06]
504    (519.52, 690.06]
505     (690.06, 860.6]
506     (690.06, 860.6]
507     (690.06, 860.6]
508     (690.06, 860.6]
509     (690.06, 860.6]
510     (690.06, 860.6]
511    (519.52, 690.06]
512    (519.52, 690.06]
513    (519.52, 690.06]
514    (519.52, 690.06]
515    (519.52, 690.06]
516     (7.047, 178.44]
Name: DC, Length: 517, dtype: category
Categories (5, interval[float64]): [(7.047, 178.44] < (178.44, 348.98] < (348.98, 519.52] < (519.52, 690.06] < (690.06, 860.6]]

# Encoding

In [68]:
#OneHotEncoder不好用

In [77]:
df_new = pd.get_dummies(data = df,columns=['month','day','DC_bi'])

# missing values

In [70]:
df.head()

   X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area  DC_bi
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0    1.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0    1.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0    1.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0    1.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0    1.0

In [71]:
df.loc[df['DC']>=600,'DC_na'] = np.nan
df.loc[df['DC']<600,'DC_na'] = df['DC']
df.head()

,X,Y,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area,DC_bi,DC_na
0,7,5,mar,fri,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,0.0,1.0,94.3
1,7,4,oct,tue,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,0.0,1.0,NaN
2,7,4,oct,sat,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,0.0,1.0,NaN
3,8,6,mar,fri,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,0.0,1.0,77.5
4,8,6,mar,sun,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,0.0,1.0,102.2

In [72]:
from sklearn.preprocessing import Imputer  #使用平均数，中位数，众数来填充
im = Imputer()
im.fit_transform(df['DC_na'].values.reshape(-1,1))

array([[  94.3       ],
       [ 264.79289617],
       [ 264.79289617],
       [  77.5       ],
       [ 102.2       ],
       [ 488.        ],
       [ 495.6       ],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [  80.8       ],
       [ 264.79289617],
       [  70.8       ],
       [  97.1       ],
       [ 264.79289617],
       [ 264.79289617],
       [ 200.        ],
       [ 537.4       ],
       [ 594.2       ],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [  67.6       ],
       [ 366.7       ],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 442.9       ],
       [  64.7       ],
       [ 103.8       ],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [  34.        ],
       [  43.        ],
       [ 102.2       ],
       [ 102.2       ],
       [ 466.6       ],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [  77.5       ],
       [  97.8       ],
       [ 264.79289617],
       [  77.5       ],
       [ 264.79289617],
       [ 264.79289617],
       [  26.6       ],
       [  43.        ],
       [ 103.8       ],
       [ 529.8       ],
       [ 561.6       ],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [  80.8       ],
       [ 264.79289617],
       [  80.8       ],
       [ 488.        ],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [  30.2       ],
       [  15.5       ],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [   9.3       ],
       [  57.3       ],
       [  74.3       ],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [  57.3       ],
       [  77.5       ],
       [ 264.79289617],
       [ 264.79289617],
       [  67.6       ],
       [  67.6       ],
       [  80.8       ],
       [  80.8       ],
       [  86.6       ],
       [ 466.6       ],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 103.8       ],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [  87.2       ],
       [  64.7       ],
       [ 102.2       ],
       [ 264.79289617],
       [  67.6       ],
       [ 594.2       ],
       [ 264.79289617],
       [ 264.79289617],
       [ 313.4       ],
       [ 264.79289617],
       [ 264.79289617],
       [ 513.3       ],
       [ 529.8       ],
       [ 296.3       ],
       [ 513.3       ],
       [ 578.8       ],
       [  86.6       ],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 433.3       ],
       [ 355.2       ],
       [ 424.1       ],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [  86.6       ],
       [ 578.8       ],
       [ 100.4       ],
       [ 264.79289617],
       [ 264.79289617],
       [  55.        ],
       [ 264.79289617],
       [ 570.5       ],
       [  97.8       ],
       [ 578.8       ],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [  55.2       ],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [  48.3       ],
       [ 264.79289617],
       [ 586.7       ],
       [ 264.79289617],
       [ 102.2       ],
       [ 264.79289617],
       [  89.4       ],
       [  92.4       ],
       [  97.8       ],
       [ 578.8       ],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 586.7       ],
       [  55.2       ],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [  83.7       ],
       [  32.1       ],
       [ 264.79289617],
       [ 100.4       ],
       [ 264.79289617],
       [ 594.2       ],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 594.2       ],
       [ 264.79289617],
       [ 103.8       ],
       [  80.8       ],
       [  80.8       ],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [  86.6       ],
       [ 264.79289617],
       [ 264.79289617],
       [ 103.8       ],
       [ 309.9       ],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 480.8       ],
       [ 264.79289617],
       [ 480.8       ],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [   7.9       ],
       [  43.5       ],
       [  85.3       ],
       [ 589.9       ],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 503.6       ],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 565.5       ],
       [ 264.79289617],
       [ 264.79289617],
       [ 581.1       ],
       [ 581.1       ],
       [ 264.79289617],
       [ 264.79289617],
       [ 542.        ],
       [ 573.        ],
       [ 573.        ],
       [ 264.79289617],
       [ 264.79289617],
       [ 550.3       ],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 353.5       ],
       [ 354.6       ],
       [ 352.        ],
       [ 349.7       ],
       [ 349.7       ],
       [ 349.7       ],
       [ 349.7       ],
       [ 352.6       ],
       [ 349.7       ],
       [ 353.5       ],
       [  18.7       ],
       [  15.8       ],
       [ 411.8       ],
       [ 437.7       ],
       [ 474.9       ],
       [ 474.9       ],
       [ 474.9       ],
       [ 474.9       ],
       [ 474.9       ],
       [ 466.3       ],
       [ 430.8       ],
       [ 440.9       ],
       [ 430.8       ],
       [ 290.8       ],
       [ 290.8       ],
       [ 377.2       ],
       [ 233.8       ],
       [ 298.1       ],
       [ 298.1       ],
       [ 232.1       ],
       [ 232.1       ],
       [ 113.8       ],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 520.5       ],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [  30.6       ],
       [ 171.4       ],
       [ 458.8       ],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [  30.6       ],
       [ 264.79289617],
       [ 264.79289617],
       [  58.3       ],
       [ 264.79289617],
       [ 264.79289617],
       [  25.6       ],
       [  46.7       ],
       [  56.9       ],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 297.7       ],
       [ 297.7       ],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [  55.        ],
       [ 264.79289617],
       [ 450.2       ],
       [  52.8       ],
       [  43.6       ],
       [ 442.1       ],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 575.8       ],
       [  28.3       ],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 376.6       ],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [  41.6       ],
       [ 368.3       ],
       [ 264.79289617],
       [ 100.7       ],
       [ 264.79289617],
       [  28.3       ],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 567.2       ],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [  16.2       ],
       [  16.2       ],
       [  15.3       ],
       [  36.9       ],
       [  41.1       ],
       [  43.5       ],
       [  25.6       ],
       [  25.6       ],
       [  73.7       ],
       [ 229.        ],
       [ 252.6       ],
       [ 316.7       ],
       [ 350.2       ],
       [ 395.        ],
       [ 423.4       ],
       [ 423.4       ],
       [ 431.6       ],
       [ 560.        ],
       [ 560.        ],
       [ 587.1       ],
       [ 587.1       ],
       [ 587.1       ],
       [ 596.3       ],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 264.79289617],
       [ 106.7       ]])

In [73]:
df.shape

(517, 15)

# PCA vs SCD

In [75]:
from sklearn.feature_selection import VarianceThreshold,SelectKBest,chi2,SelectPercentile

导入特征选择库中的VarianceThreshold用于通过方差选择特征。方差为0的特征会被自动移除。剩下的特征按设定的方差的阈值进行选择。
SelectKBest计算特征与结果间的相关性，并选择相关性最高的特征。

http://bluewhale.cc/2016-11-25/use-scikit-learn-for-feature-selection.html

In [ ]:
v = VarianceThreshold(0.5)
v.fit_transform(modelData.fillna(-999)).shape

In [85]:
from sklearn.feature_selection import f_regression